### ISSUE TITLE
Most of the answers are WRONG!

### ISSUE THREAD

**Issue by ttma1046** [sudheerj/angular-interview-questions#12]
Lazy loading is one of the most useful concepts of Angular Routing. 
It helps us to download the 
**web pages** (no, it should be the  `frontend javascript bundles` generated by angular)
 in chunks instead of downloading everything in a big bundle.

so many incorrect answers.

**Comment by sudheerj** [comment]
No, It is used to asynchronously load the feature module for routing whenever required. Please check Angular8 features.
