### ISSUE TITLE
question 10.

### ISSUE THREAD

**Issue by GaryBirges** [sudheerj/angular-interview-questions#15]
Hi there,

you mention 3 parts of the ngModule, but there are two more and one of them is "essential":
-the providers array, where you have to register your services
-entryComponents, the components which can be dynamically loaded to the view.

could you please update your answer?
Cheers,
Gary

**Comment by GaryBirges** [comment]
Please close it, I'll pull it later!

**Comment by sudheerj** [comment]
Updated. Thanks.
