### ISSUE TITLE
Description of 18 point is not present.

### ISSUE THREAD

**Issue by akib1997** [sudheerj/angular-interview-questions#54]
Point 18: How is Dependency Hierarchy formed?

There is no description.

**Comment by sudheerj** [comment]
Okay..@akib1997 Can you create pull request if possible

**Comment by VasileDurlesteanu** [comment]
@sudheerj I've created a pull request several minutes ago. If it passes the review, probably the issue can be marked as closed.
Best regards!

**Comment by sudheerj** [comment]
@VasileDurlesteanu Thanks for PR. It has been merged.
